export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST'
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS'
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL'

export const IMAGE_CREATE_REQUEST = 'IMAGE_CREATE_REQUEST'
export const IMAGE_CREATE_SUCCESS = 'IMAGE_CREATE_SUCCESS'
export const IMAGE_CREATE_FAIL = 'IMAGE_CREATE_FAIL'
export const IMAGE_CREATE_RESET = 'IMAGE_CREATE_RESET'

export const IMAGE_UPDATE_REQUEST = 'IMAGE_UPDATE_REQUEST'
export const IMAGE_UPDATE_SUCCESS = 'IMAGE_UPDATE_SUCCESS'
export const IMAGE_UPDATE_FAIL = 'IMAGE_UPDATE_FAIL'
export const IMAGE_UPDATE_RESET = 'IMAGE_UPDATE_RESET'

export const IMAGE_DETAILS_REQUEST = 'IMAGE_DETAILS_REQUEST'
export const IMAGE_DETAILS_SUCCESS = 'IMAGE_DETAILS_SUCCESS'
export const IMAGE_DETAILS_FAIL = 'IMAGE_DETAILS_FAIL'
